version: '3'
services:
  app:
    build: .
    ports:
      - "4000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Task
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
volumes:
  mongo-data:
  redis_data: